### PR TITLE
Take theming info from initial state so it only updates once

### LINKED ISSUE #945: Request for notifications-new.svg is made and immediately cancelled
### Steps to reproduce
1. Log in and see your dashboard
2. Check the network activity in the browser debugger - you'll see /apps/notifications/img/notifications-new.svg (canceled)
3. Check the nginx webserver log, you'll see /apps/notifications/img/notifications-new.svg code 499 (client closed the connection)

### Expected behaviour
Why on earth does the FE make a request and immediately cancel it? This causes a code 499 log entry in nginx. I'm unhappy about this as I want to monitor the logs with Fail2Ban as a security measure, and all "weird" messages are a headache, in fact all messages which are avoidable are unwanted, as when the logs get too long then race conditions happen bewteen the webserver writing logs and fail2ban monitoring them.

### Actual behaviour
499, client cancels the request it just made

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** Nextcloud 20.0.9

**Where did you install Nextcloud from:** Manually years ago, Updater since

**Signing status:** ?

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.7
  - support: 1.3.0
  - survey_client: 1.8.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - firstrunwizard
  - systemtags
  - user_ldap
```

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.reeves.one"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/owncloud.reeves.one",
        "dbtype": "mysql",
        "version": "20.0.9.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": "2",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en",
        "log_rotate_size": 10485760,
        "check_for_working_htaccess": false,
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_scale_factor": 1,
        "preview_max_filesize_image": 10,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Krita"
        ],
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "filelocking.ttl": 3600,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 1
        },
        "trashbin_retention_obligation": "auto",
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "check_for_working_wellknown_setup": false,
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable",
        "blacklisted_files": []
    }
}
```

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** FF

**Operating system:** Kubunut 18.04

### Logs

#### Nextcloud log (data/owncloud.log)
```
Only 2 entries, neither relevant
```

#### Browser log (all errors when loading dashboard)
```
activity-sidebar.js?v=c557ce13-1:603 Uncaught TypeError: Cannot read property 'extend' of undefined
    at activity-sidebar.js?v=c557ce13-1:603
    at activity-sidebar.js?v=c557ce13-1:803
comments.js?v=c557ce13-1:1 Uncaught TypeError: Cannot read property 'extend' of undefined
    at comments.js?v=c557ce13-1:1
    at Module.<anonymous> (comments.js?v=c557ce13-1:1)
    at n (comments.js?v=c557ce13-1:1)
    at comments.js?v=c557ce13-1:1
    at comments.js?v=c557ce13-1:1
files_versions.js?v=c557ce13-1:1 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (files_versions.js?v=c557ce13-1:1)
    at n (files_versions.js?v=c557ce13-1:1)
    at files_versions.js?v=c557ce13-1:1
    at files_versions.js?v=c557ce13-1:1
viewer-main.js?v=c557ce13-1:403 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
dashboard.js?v=c557ce13-1:87 GET https://owncloud.reeves.one/index.php/apps/mail/api/avatars/url/m.bariola%40gmail.com 404
dashboard.js?v=c557ce13-1:338 GET https://owncloud.reeves.one/ocs/v2.php/apps/user_status/api/v1/statuses/daniel 404
dashboard.js?v=c557ce13-1:338 GET https://owncloud.reeves.one/ocs/v2.php/apps/user_status/api/v1/statuses/enjell 404
dashboard.js?v=c557ce13-1:87 GET https://owncloud.reeves.one/index.php/apps/mail/api/avatars/url/streng-privat%40posteo.de 404
dashboard.js?v=c557ce13-1:87 GET https://owncloud.reeves.one/index.php/apps/mail/api/avatars/url/annemollenhauer%40yahoo.com 404
dashboard.js?v=c557ce13-1:87 GET https://owncloud.reeves.one/index.php/apps/mail/api/avatars/url/mlh.heiden%40gmail.com 404
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #945 

By using the theming info from initial state directly instead of OCA.Theming, it is available immediately and doesn't create another icon request which is canceled

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

File: src/App.vue [hunk 1]
```diff
@@ -68,10 +69,11 @@ export default {
 
 	data() {
 		return {
-			webNotificationsGranted: null,
+			webNotificationsGranted: false,
 			hadNotifications: false,
 			backgroundFetching: false,
 			shutdown: false,
+			invertedTheme2: false,
```
Comment (juliushaertl) [inline src/App.vue:76]: Oh just catched

```suggestion
			invertedTheme: false,
```

**Review by juliushaertl — CHANGES_REQUESTED** [review]

File: src/App.vue (hunk 1 above)
Comment (nickvergessen) [reply src/App.vue:76]: ah was from a testing attempt

**Review by juliushaertl — APPROVED** [review]
