### PR TITLE
fix(multi-tab): Fix interactions when multiple tabs are active

### LINKED ISSUE #469: Click on notification bell should check for new notifications
- be in files view
- see " no notification"
- do something that triggers a notification for this user, e.g. federated share
- open up notification -> still nothing
- one has to reload entire website to get this notification

--> click on "notification bell" should check for new notifications?

### LINKED ISSUE #2155: [Bug]: notifications should be synced across open browser tabs
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

1. have multiple tabs with NC open
2. receive notifications
3. dismiss notifications in one tab
4. go to different tab
5. the dismissed notifications are still there

### Expected behavior

- notifications should be synced across open browser tabs
- dismissed notifications should be dismissed in all browser tabs

### Nextcloud Server version

30

### Additional info

it is very common that people have NC open in multiple tabs/windows

it is confusing that a user action in one tab is not respected in another tab

maybe related? https://github.com/nextcloud/server/issues/13980

### PR DESCRIPTION
**Pull request by nickvergessen**
- Deleting a notification in a tab makes that tab the active one - Prevents the "reappearing" scenario
- Deleting all notifications makes the tab the active one - Prevents the "reappearing" scenario
- Clicking the bell loads the newest state from the shared storage - Helps seeing the notification in the site when you saw a browser notification in your OS, but the current tab is not the active one and did not reload it yet
- Fix #469 
- Fix #2155

### Previous "reappearing" scenario
- You need 2 tabs Tab1 and Tab2
- Have notifications
- Tab1 load the page (Tab1 is now active)
- Open notification menu
- Wait 10 seconds
- Tab2 load the page (Tab2 is now active)
- Open notification menu
- Monitor both browser consoles in parallel
- After Tab2 loaded notifications with 304
- (within 20 seconds) Delete a notification in Tab1
- (at the end of the 20 seconds) Tab1 "loads notifications" from browser storage of Tab2 (last active tab)
- Tab1 shows the notification again
- Tab2 loads notifications with 200
- Tab1 "loads notifications" from browser storage of Tab2 (last active tab)
- Tab1 drops the notification again

### CODE REVIEW

File: src/NotificationsApp.vue [hunk 1]
```diff
@@ -255,6 +258,7 @@ export default {
 
 		onOpen() {
 			this.requestWebNotificationPermissions()
+			this._fetch()
```
Comment (Antreesy) [inline src/NotificationsApp.vue]: Works better for me that way (reassigns active tab, does not make extra request)

```suggestion
			setCurrentTabAsActive(this.tabId)
```

Comment (nickvergessen) [reply src/NotificationsApp.vue]: But then the tab still does not have the newest data directly
`setCurrentTabAsActive` basically does not fill/update `this.notifications`

Comment (Antreesy) [reply src/NotificationsApp.vue]: Maybe it's worth splitting. I see fetching goes as a side effect, when set an active tab
