### PR TITLE
fix(notification): Fix color of notification icon in browser notifica…

### LINKED ISSUE #2839: Web push activity notifications have low contrast when using dark mode on desktop
## Summary

The notifications a user receives when subscribing for updates to e.g. share modifications have an accessibility problem: when the user uses web push notifications and their OS is in dark mode, the activity icon in the notification is black, which combined with the dark background of the notification makes it really hard to see.

We should discuss to see which solution we can implement for this.

## How to reproduce

1. Use a OS with Dark Theme support or with a theme which makes the background of notifications dark
2. Enable the `notifications` and `activity` apps on a Nextcloud instance
3. Enable HTTPS in your instance (in Julius' dev setup [can be done easily](https://juliusknorr.github.io/nextcloud-docker-dev/basics/ssl/#https))
4. Open a browser tab pointing at your instance using `https://...`
5. Make sure to accept the browser's request asking for permissions to display notifications
6. With User A, navigate to "Personal Settings -> Notifications" and enable push notifications for the action you wish to test
7. With User B, trigger the action that will produce a notification for User B
8. Observe the received notification (from your browser!) it will have a black icon for the activity, which is barely visible.

#### KDE + Firefox

Image

#### Windows 11 + Firefox

Image

### PR DESCRIPTION
**Pull request by nickvergessen**
…tions

- Fix #2839 
- The content of this PR was partly or fully generated using AI

Before | After - Bright theme with dark icon | After - Dark theme with bright icon
---|---|---
grafik | Bildschirmfoto vom 2026-03-16 18-07-40 | Bildschirmfoto vom 2026-03-16 18-08-05

### CODE REVIEW

File: src/services/webNotificationsService.js [hunk 1]
```diff
@@ -10,22 +10,68 @@ import { generateFilePath } from '@nextcloud/router'
...
+
+			ctx.fillStyle = getComputedStyle(document.body).getPropertyValue('--color-primary-element')
+			ctx.beginPath()
+			ctx.arc(size / 2, size / 2, size / 2, 0, 2 * Math.PI)
+			ctx.fill()
+
+			// Apply invert filter when the font-color is not supposed to be black
+			if (getComputedStyle(document.body).getPropertyValue('--color-primary-text') !== '#000000') {
+				ctx.filter = 'invert(100%)'
+			}
```
Comment (Antreesy) [inline src/services/webNotificationsService.js:38]: We have a CSS variable for that, it feels safe to use, rather than compare to hardcoded #000 color
```suggestion
			ctx.filter = getComputedStyle(document.body).getPropertyValue('--primary-invert-if-dark')
```

File: src/services/webNotificationsService.js [hunk 2]
```diff
@@ -10,22 +10,68 @@ import { generateFilePath } from '@nextcloud/router'
...
+		const img = new Image()
+		img.crossOrigin = 'anonymous'
+		img.onload = () => {
+			const canvas = document.createElement('canvas')
+			const size = 32 + 4 * (Math.max(img.width, img.height) || 16)
+			canvas.width = size
+			canvas.height = size
+			const ctx = canvas.getContext('2d')
+
+			ctx.fillStyle = getComputedStyle(document.body).getPropertyValue('--color-primary-element')
```
Comment (Antreesy) [inline src/services/webNotificationsService.js:30]: We noticed this function might be a bit heavy if called often. Maybe we can cache the result for the second use of it?
```suggestion
			const computedBodyStyle = getComputedStyle(document.body)
			ctx.fillStyle = computedBodyStyle.getPropertyValue('--color-primary-element')
```
